### PR TITLE
Peer deps

### PR DESCRIPTION
**Pull request by sullenor**

### CODE REVIEW

**Comment by joeybaker** [comment]
:+1: You'll probably want to also specify these as devDependencies too so the tests will pass :)

**Comment by sullenor** [comment]
I checked it with npm@3.2.2 and looks like it still installs peerDeps. I also saw your commits in the fork so I assume you had some problems with it?

**Comment by joeybaker** [comment]
hmmm… no, I didn't actually try it. I just have the habit of putting them in devDeps since they won't be installed in the future. Interesting that it's not a problem.

**Comment by sullenor** [comment]
Sounds logical :) Let me update it

**Comment by sullenor** [comment]
Thanks :)

**Comment by joeybaker** [comment]
Thank you!

**Pull request merged**
